version: "3.8"
services:
  bot:
    restart: unless-stopped
    env_file: .env
    image: ericrigsb/pythonfeet
    working_dir: /usr/src/app
    volumes: 
      - ./app:/usr/src/app
      - ./lastid:/usr/lastid
    networks:
      - host
    command: bash -c "pip install -r requirements.txt && python3 -u premiere.py"
networks:
  host:
