name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy App
      uses: Core2Goal/ssh-action@v1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        private_key: ${{ secrets.SSHKEY }}
        script: |
          cd projects/bitl_premiere
          git pull
          docker compose restart